### ISSUE TITLE
Incompatible pointer types error

### ISSUE THREAD

**Issue by CasualRascal** [AyatanaIndicators/libayatana-indicator#24] opened 2020-08-26 17:59 UTC
Can you replicate this error?
[libayatana-indicator-0.8.1.txt](https://github.com/AyatanaIndicators/libayatana-indicator/files/5131482/libayatana-indicator-0.8.1.txt)

**Comment by sunweaver** [comment] 2020-08-27 07:11
@CasualRascal: Can you provide more context?

Against what GLib version are you building? What compiler version? On what distro? etc.

Thanks

**Comment by CasualRascal** [comment] 2020-08-27 07:29
Hi, thank you for the reply,
GLib 2.63
clang 9.0.1
OpenMandriva Lx 4.1

**Comment by tari01** [comment] 2021-05-24 21:08
@CasualRascal @sunweaver 

We now have automated builds using both `clang` and `gcc` - no failing builds on our side. Can we close this?

**Comment by sunweaver** [comment] 2021-06-04 13:53
@CasualRascal: closing this one now, due to lack of feedback and unreproducibility as of today.

**Closed by sunweaver** 2021-06-04 13:53 UTC
